version: '3'
services:
  electrumx-pgt:
    build: ./electrumx
    network_mode: "host"
    restart: always
    volumes:
      - electrumx-data-pgt:/data
    environment:
      - HOME=/data
      - DB_DIRECTORY=/data
      - COIN=PGT
      - DAEMON_URL=http://${RPC_USER}:${RPC_PASS}@127.0.0.1:46705/
      - RPC_HOST=0.0.0.0
      - RPC_PORT=8000
      - HOST=0.0.0.0
      - TCP_PORT=10000

volumes:
  electrumx-data-pgt:
    driver: local
